school21_case/home/urls.py
from django.urls import path
from .views import home, about, help_

urlpatterns = [
    path("", home, name="home"),
    path("about", about, name="about"),
    path("help", help_, name="help"),
]

school21_case/school21_case/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("users/", include("users.urls")),
    path("groups/", include("groups.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

school21_case/users/urls.py
from django.urls import path
from .views import (
    add_friend,
    my_profile,
    edit_profile,
    remove_friend,
    remove_list_friend,
    search_profile,
    sign_up,
    register,
    user_logout,
    confirm_2fa,
    ProfileDetailView,
    FriendsListView,
)

urlpatterns = [
    path("profile/detail/<int:pk>", ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/search/", search_profile, name="profile_search"),
    path("my-profile/", my_profile, name="my_profile"),
    path("my-profile/edit", edit_profile, name="profile_edit"),
    path("friends/<int:pk>", FriendsListView.as_view(), name="friends_list"),
    path("add-friend/<int:pk>", add_friend, name="add_friend"),
    path("remove-friend/<int:pk>", remove_friend, name="remove_friend"),
    path("remove-list-friend/<int:pk>", remove_list_friend, name="remove_lfriend"),
    path("login/", sign_up, name="sign_up"),
    path("verify/", confirm_2fa, name="confirm_2fa"),
    path("logout/", user_logout, name="logout"),
    path("register/", register, name="register"),
]

school21_case/users/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User


gender_choices = [("мужской", "Мужской"), ("женский", "Женский")]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    nickname = models.CharField(unique=True, max_length=32, verbose_name="Никнейм")
    description = models.CharField(max_length=256, null=True, blank=True, verbose_name="Описание профиля")

    name = models.CharField(blank=True, null=True, verbose_name="Имя")
    surname = models.CharField(blank=True, null=True, verbose_name="Фамилия")
    lastname = models.CharField(blank=True, null=True, verbose_name="Отчество")
    age = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(99)], blank=True, null=True, verbose_name="Возраст"
    )
    gender = models.CharField(choices=gender_choices, null=True, blank=True, verbose_name="Пол")

    avatar = models.ImageField(upload_to="avatars/", null=True, blank=True, verbose_name="Аватар")

    nickname_tg = models.CharField(blank=True, null=True, verbose_name="Никнейм в Telegram")
    nickname_ds = models.CharField(blank=True, null=True, verbose_name="Никнейм в Discord")
    study_at = models.CharField(blank=True, null=True, verbose_name="Учебное заведение")

    interests = models.ManyToManyField(
        "groups.Interest", related_name="related_profiles", blank=True, verbose_name="Интересы"
    )
    groups = models.ManyToManyField("groups.Group", related_name="groups", blank=True, verbose_name="Группы")
    friends = models.ManyToManyField("self", blank=True, null=True, verbose_name="Друзья")

    def get_absolute_url(self):
        return reverse("profile", args=[str(self.id)])

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

school21_case/users/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Profile


class ProfileSearchForm(forms.Form):
    query = forms.CharField(
        max_length=32,
        widget=forms.TextInput(
            attrs={
                "class": "form-control input-field",
                "placeholder": "Введите ник пользователя...",
            }
        ),
    )


class LoginForm(forms.Form):
    email = forms.EmailField(label="Электоронная почта", widget=forms.EmailInput)
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "username"]

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
            profile = Profile(user=user, nickname=self.cleaned_data["username"])
            profile.save()

        return user


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = [
            "user",
            "created_at",
            "is_active",
            "groups",
            "interests",
            "avatar",
            "friends",
        ]

school21_case/users/views.py
from random import randint

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from django.db.models import Q
from django.core.mail import send_mail

from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.views.generic import DetailView, ListView

from school21_case.settings import EMAIL_HOST_USER

from .forms import ProfileSearchForm, LoginForm, RegistrationForm, ProfileEditForm
from groups.models import Interest


class ProfileDetailView(DetailView):
    model = User
    template_name = "users/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = ProfileSearchForm()
        context["tags"] = Interest.objects.all()
        return context


@login_required
def search_profile(request: HttpRequest):
    search_query_raw = ProfileSearchForm(request.POST)

    if request.method == "POST" and search_query_raw.is_valid():
        search_query = search_query_raw.cleaned_data

        query = search_query.get("query")
        tags = search_query_raw.data.getlist("tags[]")

        profile = User.objects.filter(
            Q(profile__nickname__icontains=query)
            | Q(profile__name__icontains=query)
            | Q(profile__surname__icontains=query)
            | Q(profile__lastname__icontains=query)
        )

        if tags:
            profile = profile.filter(profile__interests__id__in=tags).distinct()

        return render(
            request,
            "users/user_search.html",
            context={
                "users": profile.all(),
                "search_form": ProfileSearchForm(),
                "tags": Interest.objects.all(),
                "search_query": query,
            },
        )
    return render(
        request,
        "users/user_search.html",
        context={"search_form": ProfileSearchForm(), "tags": Interest.objects.all()},
    )


def sign_up(request: HttpRequest):
    search_form = ProfileSearchForm()

    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]

            user_item = User.objects.filter(email=email).first()

            if user_item:
                user = authenticate(request, username=user_item.username, password=password)
                if user:
                    otp = randint(1000, 999999)
                    request.session["otp"] = otp
                    request.session["email"] = email
                    send_mail(
                        "Ваш код двухфакторной аутенфикации",
                        f"Код: {otp}",
                        EMAIL_HOST_USER,
                        [user.email],
                        fail_silently=False,
                    )
                    return redirect("confirm_2fa")

    return render(
        request,
        "users/login.html",
        {
            "login_form": LoginForm(),
            "search_form": search_form,
            "tags": Interest.objects.all(),
        },
    )


def confirm_2fa(request: HttpRequest):
    if request.method == "POST":
        entered_otp = request.POST.get("otp")

        if entered_otp == str(request.session.get("otp")):
            user = User.objects.filter(email=request.session.get("email")).first()
            login(request, user)
            return redirect("home")
        else:
            return render(
                request,
                "users/confirm_2fa.html",
                {
                    "search_form": ProfileSearchForm(),
                    "tags": Interest.objects.all(),
                    "email": request.session.get("email"),
                    "error": "Не верный код",
                },
            )

    return render(
        request,
        "users/confirm_2fa.html",
        {
            "search_form": ProfileSearchForm(),
            "tags": Interest.objects.all(),
            "email": request.session.get("email"),
        },
    )


def register(request: HttpRequest):
    search_form = ProfileSearchForm()

    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if not form.errors:
            exist_item = User.objects.filter(email=form.cleaned_data["email"]).first()

            if not exist_item:
                data = form.cleaned_data

                form.save()
                user = authenticate(request, username=data["username"], password=data["password1"])

                login(request, user)
                return redirect("home")

            form.add_error("email", "Пользователь с таким адресом электронной почты уже существует.")

        return render(request, "users/register.html", {"reg_form": form, "search_form": search_form})

    form = RegistrationForm()
    return render(
        request,
        "users/register.html",
        {
            "reg_form": form,
            "search_form": search_form,
            "tags": Interest.objects.all(),
        },
    )


def user_logout(request: HttpRequest):
    if request.user.is_authenticated:
        logout(request)
    return redirect("sign_up")


@login_required
def my_profile(request: HttpRequest):
    return render(
        request,
        "users/profile.html",
        {
            "user": request.user,
            "search_form": ProfileSearchForm(),
            "tags": Interest.objects.all(),
        },
    )


@login_required
def edit_profile(request: HttpRequest):
    profile = request.user.profile
    if request.method == "POST":
        form = ProfileEditForm(request.POST, instance=profile, use_required_attribute=False)

        if not form.errors:
            instance = form.save(commit=False)
            tags = request.POST.getlist("interests[]")

            if 0 < len(tags) <= 5:
                instance.interests.set(tags)
            else:
                form.add_error(None, "Вы можете выбрать не более 5 интересов.")

            if request.FILES.get("avatar"):
                profile.avatar = request.FILES.get("avatar")
                profile.save()

            if not form.errors:
                instance.save()
                return redirect("my_profile")

        return render(
            request,
            "users/profile_edit.html",
            {
                "search_form": ProfileSearchForm(),
                "editable": form,
                "profile": profile,
                "tags": Interest.objects.all(),
            },
        )

    return render(
        request,
        "users/profile_edit.html",
        {
            "search_form": ProfileSearchForm(),
            "editable": ProfileEditForm(use_required_attribute=False, instance=request.user.profile),
            "profile": request.user.profile,
            "tags": Interest.objects.all(),
        },
    )


class FriendsListView(ListView):
    template_name = "users/friends.html"
    context_object_name = "friends"
    paginate_by = 6

    def get_queryset(self):
        profile_id = self.kwargs.get("pk")
        user = get_object_or_404(User, pk=profile_id)
        return user.profile.friends.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = ProfileSearchForm()
        context["tags"] = Interest.objects.all()
        context["profile_pk"] = self.kwargs.get("pk")
        return context


@login_required
def add_friend(request: HttpRequest, pk: int):
    user = get_object_or_404(User, pk=pk)
    if request.user != user:
        request.user.profile.friends.add(user.profile)
        user.profile.friends.add(request.user.profile)
    return redirect("profile_detail", pk=pk)


@login_required
def remove_friend(request: HttpRequest, pk: int):
    user = get_object_or_404(User, pk=pk)
    if request.user != user:
        request.user.profile.friends.remove(user.profile)
        user.profile.friends.remove(request.user.profile)
    return redirect("profile_detail", pk=pk)


@login_required
def remove_list_friend(request: HttpRequest, pk: int):
    user = get_object_or_404(User, pk=pk)
    if request.user != user:
        request.user.profile.friends.remove(user.profile)
        user.profile.friends.remove(request.user.profile)
    return redirect("friends_list", pk=request.user.profile.id + 1)

school21_case/templates/users/confirm_2fa.html
{% extends "base.html" %}
{% load static %}
{% load add_class %}

{% block title %}Вход{% endblock %}
{% block description %}Проверка{%endblock %}

{% block content %}

<div class="container">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title"><i class="fas fa-user-secret"></i> Проверка</h4>
      </div>
      <div class="card-body">

      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card card-attention">
          <div class="card-body">
            <div class="d-flex justify-content-center">
              <h4 class="card-title text-info">Введите код который был отправлен на почту <span class="card-title gradient-right">{{ email }}</span></h4>
            </div>
            <div class="d-flex justify-content-center mb-3">
              <hr class="under-info" style="width: 50%;">
            </div>
              <form method="POST">
                {% csrf_token %}
                <div class="col-md-4 ms-auto me-auto">
                  <input class="form-control input-field text-center type="text" name="otp" id="id_otp" required>
                  <div class="text-center">
                    <button class="btn btn-primary mt-3" type="submit">Подтвердить</button>
                  </div>
                </div>
              </form>
              {% if error %}
              <div class="d-flex justify-content-center">
                <h4 class="card-title text-info text-danger">Неверный код</h4>
              </div>
              {% endif %}
          </div>
        </div>
      </form>

      </div>
    </div>
</div>

{% endblock %}

school21_case/templates/users/friends.html
{% extends "base.html" %}
{% load static %}

{% block title %}Участники группы {{ group.name }}{% endblock %}
{% block description %}{{ group.description|truncatewords:15 }}{%endblock %}

{% block content %}

<div class="container">
  <div class="card">
    <div class="card-header">
      <div class="card-head-row card-tools-still-right">
        <h4 class="card-title gradient-right">
          {% if request.user.password == user.password %}
          Мои друзья {{ friends.all|length }}
          {% else %}
          Друзья пользователя {{ user.profile.nickname }}
          {% endif %}
        </h4>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col">
          {% for friend in friends %}
            <div class="card card-attention">
              <div class="card-body user-card d-flex align-items-center">
                <div class="avatar avatar-xxl me-3">
                  {% if friend.avatar %}
                    <img class="avatar-xxl rounded-circle" src="{{ friend.avatar.url }}">
                  {% else %}
                    <img class="avatar-xxl rounded-circle" src="{% static 'img/noavatar.png' %}">
                  {% endif %}
                </div>
                <div class="user-info">
                  <a class="text-decoration-none" href="{% url 'profile_detail' pk=friend.user.pk %}" >
                    <span class="card-title">
                      {{ friend.nickname }}
                    </span>
                  </a>
                  <span class="card-text d-block" style="color: azure; font-size: 15px;">
                    {{ friend.description|default:"Описание отстутствует"|truncatewords:15 }}
                  </span>
                  <p class="card-category">{% for tag in friend.interests.all %}#{{ tag }} {% endfor %}</p>
                  <a class="card-category mt-2" href="{% url 'remove_lfriend' pk=friend.pk %}"><i class="far fa-trash-alt"></i> Удалить из друзей</a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>

        <div class="row-md">
          {% if page_obj.has_next %}
          <div class="col">
            <div class="site-pagination p-3">
              {% if page_obj.has_previous %}
                {% if page_obj.previous_page_number > 1 %}
                <a href="?page=1">1</a>
                {% endif %}
                <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
              {% endif %}

              <span class="active">{{ page_obj.number }}</span>

              {% if page_obj.has_next %}
                  <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                  {% if page_obj.next_page_number < page_obj.paginator.num_pages %}
                      <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                  {% endif %}
              {% endif %}
            </div>
          </div>
          {% endif %}
          <div class="col">
            <div class="d-flex justify-content-center">
              <a href="{% url 'profile_detail' pk=profile_pk %}">
                <button class="btn btn-primary">Назад</button>
              </a>
            </div>
          </div>
        </div>

    </div>
  </div>
</div>

{% endblock %}

school21_case/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% load add_class %}

{% block title %}Вход / Регистрация{% endblock %}
{% block description %}Войти в аккаунт или зарегистрироваться{%endblock %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card card-round" style="background-color: aliceblue;">
      <div class="card-header">
        <div class="card-head-row card-tools-still-right">
          <h4 class="card-title gradient-right">Вход</h4>
        </div>
      </div>

      {% if request.user.is_authenticated %}
      <div class="card-body d-grid gap-3 justify-content-center text-center">
        <div class="col">
          <h1>Вы уже зарегистрированы как {{ request.user.profile.nickname }}</h1>
          <h2>Выйти?</h2>
        </div>

        <div class="col">
          <a href="{% url 'logout' %}" style="color: whitesmoke;">
            <button class="btn btn-danger">Да</button>
          </a>
        </div>
        
        <div class="col">
          <a href="{% url 'home' %}" style="color: whitesmoke;">
            <button class="btn btn-primary">Вернуться домой</button>
          </a>
        </div>
      </div>

      {% else %}

      <div class="card-body d-flex justify-content-center">
          <form class="row g-3" method="POST">
            {% csrf_token %}
            {% for field in login_form %}
              <div class="row-md-4">
                <div class="form-label">{{ field.label_tag }}</div>
                {{ field|add_class:"form-control" }}
              </div>
            {% endfor %}

            {% if reg_form.errors %}
              {{ reg_form.errors }}
            {% endif %}

            <div class="col-12">
              <button class="btn btn-primary" type="submit" value="Login">Войти</button>
              <button class="btn btn-primary"><a href="{% url 'register' %}" style="color: whitesmoke;">Зарегистрироваться</a></button>
            </div>
            
          </form>
          
        </div>
      {% endif %}

    </div>
  </div>
</div>

{% endblock %}

school21_case/templates/users/profile_edit.html
{% extends "base.html" %}
{% load static %}
{% load add_class %}

{% block title %}Мой профиль{% endblock %}
{% block description %}Редактирование{%endblock %}

{% block content %}

<div class="container">
  <div class="card">
    <div class="card-header">
      <div class="card-head-row card-tools-still-right">
        <h4 class="card-title"><i class="fas fa-edit"></i> Редактирование профиля</h4>
      </div>
    </div>

    <div class="card-body">
      <form method="POST" enctype="multipart/form-data">
        <div class="row">
          {% csrf_token %}
          <div class="col-md-4">
            <div class="card card-attention">

              <div class="card-body">
                <div class="avatar-container">
                  {% if user.is_authenticated %}
                  <div class="avatar avatar-xl avatar-img">
                    {% if user.profile.avatar %}
                      <img src="{{ user.profile.avatar.url }}" class="rounded-circle img-fluid border border-slimegreen" id="avatar">
                    {% else %}
                      <img src="{% static 'img/noavatar.png' %}" class="rounded-circle img-fluid border border-slimegreen" id="avatar">
                    {% endif %}
                  </div>
                  {% else %}
                  <a href="{% url 'sign_up' %}"> 
                    <i class="fas fa-sign-in-alt"></i>
                    <p>Войти / Зарегистрироваться</p>
                  </a>
                  {% endif %}
                </div>
                <input class="form-control edit-field mb-3" type="file" name="avatar" accept="image/*" id="id_avatar">

                <div class="profile-info">
                  <h2 class="card-title">{{ user.profile.nickname }}</h2>
                  <p style="color: aliceblue;">
                    {% if user.profile.description %}
                        {{ user.profile.description }}
                      {% else %}.
                        No description
                      {% endif %}
                  </p>
                </div>
              </div>

            </div>

            <div class="card card-attention">
              <div class="card-header">
                <div class="card-head-row card-tools-still-right">
                  <h4 class="card-title"><i class="fas fa-clipboard-list"></i> Ваши интересы</h4>
                </div>
              </div>
              <div class="card-body">
                {% for tag in tags %}
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="{{ tag.id }}" id="id_{{ tag|lower }}" name="interests[]"
                  {% if tag in user.profile.interests.all %}checked{% endif %}>
                  <label class="form-check-label gradient-right" for="id_{{ tag|lower }}">
                    {{ tag }}
                  </label>
                </div>
                {% endfor %}

              </div>
            </div>

          </div>

          <div class="col-md-8">
            <div class="card card-attention">
              <div class="card-header">
                <div class="card-head-row card-tools-still-right">
                  <h4 class="card-title"><i class="fas fa-address-card"></i> О себе</h4>
                </div>
              </div>
    
              <div class="card-body">
                {% for field in editable %}
                <div class="row-md-4 mb-3">
                  <div class="form-label gradient-right">{{ field.label_tag }}</div>
                  {{ field|add_class:"form-control edit-field" }}
                </div>
                {% endfor %}
              </div>

            </div>
          </div>

        </div>

        <div class="d-flex justify-content-center">
          <div class="p-2">
            <button class="btn btn-primary" type="submit" value="Save"><i class="fas fa-save"></i> Сохранить</button>
          </div>
        </div>
      </form>

        <div class="row">
          <div class="col-md-12">
            <div class="p-2">
              {% if reg_form.errors %}
                <div class="row">
                  {% if reg_form.non_field_errors %}
                      {{ reg_form.non_field_errors }}
                  {% else %}
                      {{ reg_form.errors }}
                  {% endif %}
                </div>
              {% endif %}
              <div class="d-flex justify-content-end">
                <a href="{% url 'my_profile' %}">
                  <button class="btn btn-primary">Назад</button>
                </a>
              </div>
            </div>
          </div>
        </div>

    </div>
  </div>
</div>

<script>
  document.getElementById('id_avatar').addEventListener('change', function(event) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function(e) {
        const avatarImg = document.getElementById('avatar');
        avatarImg.src = e.target.result;
      }
      reader.readAsDataURL(file);
    }
  });
</script>
{% endblock %}

school21_case/templates/users/register.html
{% extends "base.html" %}
{% load static %}
{% load add_class %}

{% block title %}Регистрация{% endblock %}
{% block description %}Зарегистрироваться на портале Школа 21 Connect{%endblock %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card card-round" style="background-color: aliceblue;">
      <div class="card-header">
        <div class="card-head-row card-tools-still-right">
          <h4 class="card-title">Регистрация</h4>
        </div>
      </div>

      {% if request.user.is_authenticated %}
      <div class="card-body d-grid gap-3 justify-content-center">
        <div class="col">
          <h1>Вы уже зарегистрированы как {{ request.user.profile.nickname }}</h1>
          <h2>Выйти?</h2>
        </div>

        <div class="col">
          <button class="btn btn-primary">
            <a href="{% url 'logout' %}" style="color: whitesmoke;">Да</a>
          </button>
        </div>
        
        <div class="col">
          <button class="btn btn-primary">
            <a href="{% url 'home' %}" style="color: whitesmoke;">Вернуться домой</a>
          </button>
        </div>
      </div>

      {% else %}

      <div class="card-body d-flex justify-content-center">

        <form class="row g-3" method="POST">
          {% csrf_token %}
          {% for field in reg_form %}
            <div class="row-md-4">
              <div class="form-label">{{ field.label_tag }}</div>
              {{ field|add_class:"form-control" }}
            </div>
          {% endfor %}

          {% if reg_form.errors %}
            {{ reg_form.errors }}
          {% endif %}

          <div class="col-12">
            <div class="mt-3 d-grid gap-3 justify-content-center">
              <button class="btn btn-primary" type="submit" value="Register">Зарегистрироваться</button>
            </div>
          </div>
          
        </form>

      </div>

      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

school21_case/templates/users/user_search.html
{% extends "base.html" %}
{% load static %}

{% block title %}Поиск пользователей{% endblock %}
{% block description %}Результаты поиска по запросу {{ search_query }}{%endblock %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card card-round">
      <div class="card-header">
        <div class="card-head-row card-tools-still-right">
          <h4 class="card-title">Пользователи</h4>
        </div>
        {% if users %}
        <p class="card-category">
          Результаты поиска по запросу {{ search_query }}
        </p>
        {% endif %}
      </div>
      <div class="card-body">
        <div class="row">
        {% if users %}
        {% for user in users %}

        <div class="col-12 col-sm-6 col-lg-4">
          <div class="card card-attention">
              <div class="card-body user-card">

                <div class="avatar avatar-xxl">
                  {% if user.profile.avatar %}
                    <img class="avatar-xxl rounded-circle" src="{{ user.profile.avatar.url }}" alt="">
                  {% else %}
                    <img class="avatar-xxl rounded-circle" src="{% static 'img/noavatar.png' %}" alt="">
                  {% endif %}
                </div>
                <div class="user-info">
                  <span class="card-title"></span>
                  <a href="{% url 'profile_detail' pk=user.pk %}"><span class="card-title">{{ user.profile.nickname }}</span></a>

                  
                  <span class="card-text" style="color: azure; font-size: 15px;">
                    {% if user.profile.description %}
                      {{ user.profile.description|truncatewords:15 }}
                    {% else %}
                      {{ user.profile.created_at }}
                    {% endif %}
                  </span>
                  <p class="card-category">{% for tag in user.profile.interests.all %}#{{ tag }} {% endfor %}</p>
                </div>

              </div>

          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="text-center mb-3">
          <h4 class="card-title gradient-right">По вашему запросу <i>{{ search_query }}</i> ничего не найдено</h4>
        </div>
        {% endif %}
      </div>

      </div>
    </div>
  </div>
</div>

{% endblock %}