school21_case/groups/urls.py
from django.urls import path
from .views import (
    delete_group,
    my_groups,
    find_groups,
    create_group,
    GroupDetailView,
    GroupMembers,
    edit_group,
    join_group,
    leave_group,
)

urlpatterns = [
    path("my-groups", my_groups, name="my_groups"),
    path("detail/<int:pk>", GroupDetailView.as_view(), name="group_detail"),
    path("detail/<int:pk>/members", GroupMembers.as_view(), name="group_members"),
    path("edit/<int:pk>", edit_group, name="edit_group"),
    path("delete/<int:pk>", delete_group, name="delete_group"),
    path("join/<int:pk>", join_group, name="join_group"),
    path("leave/<int:pk>", leave_group, name="leave_group"),
    path("find-groups", find_groups, name="find_groups"),
    path("create-group", create_group, name="create_group"),
]

school21_case/home/urls.py
from django.urls import path
from .views import home, about, help_

urlpatterns = [
    path("", home, name="home"),
    path("about", about, name="about"),
    path("help", help_, name="help"),
]

school21_case/school21_case/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("users/", include("users.urls")),
    path("groups/", include("groups.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

school21_case/groups/models.py
from django.db import models
from django.contrib.auth.models import User


class Group(models.Model):
    name = models.CharField(max_length=32, unique=True, verbose_name="Название")
    description = models.CharField(max_length=256, null=True, verbose_name="Описание")

    icon = models.ImageField(upload_to="group_icons/", null=True)
    banner = models.ImageField(upload_to="group_banners/", null=True)

    members = models.ManyToManyField(User, related_name="group_members", blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="groups_created")

    hide = models.BooleanField(default=False)
    tags = models.ManyToManyField("Interest", related_name="related_groups")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Interest(models.Model):
    name = models.CharField(max_length=32, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

school21_case/groups/forms.py
from django import forms
from .models import Group


class CreateGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ["name", "description"]


class GroupSearchForm(forms.Form):
    group_name = forms.CharField(
        max_length=32,
        widget=forms.TextInput(
            attrs={
                "class": "form-control input-field",
                "placeholder": "Введите название группы...",
            }
        ),
    )


class GroupEditForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ["name", "description"]

school21_case/groups/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, ListView
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.contrib.auth.models import User

from .models import Group, Interest
from .forms import CreateGroupForm, GroupSearchForm, GroupEditForm

from users.forms import ProfileSearchForm


@login_required
def my_groups(request: HttpRequest):
    user = request.user
    return render(
        request,
        "groups/my_groups.html",
        {
            "search_form": ProfileSearchForm(),
            "tags": Interest.objects.all(),
            "groups": user.group_members.all(),
        },
    )


@login_required
def find_groups(request: HttpRequest):
    if request.method == "POST":
        form = GroupSearchForm(request.POST)
        search_query = form.data

        name = search_query.get("group_name")
        tags = search_query.get("interests[]")

        groups = Group.objects.filter(name__icontains=name)

        if tags:
            groups = groups.filter(tags__id__in=tags).distinct()

        return render(
            request,
            "groups/find_groups.html",
            context={
                "groups": groups.all(),
                "tags": Interest.objects.all(),
                "search_form": ProfileSearchForm(),
                "find_group_form": form,
                "search_query": name,
            },
        )

    groups = Group.objects.annotate(num_members=Count("members")).order_by("-num_members").all()
    return render(
        request,
        "groups/find_groups.html",
        {
            "search_form": ProfileSearchForm(),
            "tags": Interest.objects.all(),
            "find_group_form": GroupSearchForm(),
            "just_loaded": True,
            "groups": groups,
        },
    )


class GroupDetailView(DetailView):
    model = Group
    template_name = "groups/group_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = ProfileSearchForm()
        context["tags"] = Interest.objects.all()
        return context


class GroupMembers(ListView):
    model = User
    template_name = "groups/group_members.html"
    context_object_name = "members"
    paginate_by = 6

    def get_queryset(self):
        group_id = self.kwargs.get("pk")
        return User.objects.filter(group_members=group_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = ProfileSearchForm()
        context["tags"] = Interest.objects.all()
        context["group_pk"] = self.kwargs.get("pk")
        return context


@login_required
def create_group(request: HttpRequest):
    if request.method == "POST":
        form = CreateGroupForm(request.POST)
        if not form.errors:
            group = form.save(commit=False)
            group.created_by = request.user
            group.save()

            tags = request.POST.getlist("interests[]")

            group.tags.set(tags)
            group.members.add(request.user)
            icon = request.FILES.get("icon")
            banner = request.FILES.get("banner")

            if icon:
                group.icon = icon

            if banner:
                group.banner = banner

            if len(tags):
                group.save()
                request.user.profile.groups.add(group)
                return redirect("my_groups")
            group.delete()
            form.add_error(None, "Please add at least one interest")

    return render(
        request,
        "groups/create_group.html",
        {
            "search_form": ProfileSearchForm(),
            "tags": Interest.objects.all(),
            "create_form": CreateGroupForm(),
        },
    )


@login_required
def edit_group(request: HttpRequest, pk: int):
    group = get_object_or_404(Group, pk=pk)

    if not group or request.user != group.created_by:
        return redirect("my_groups")

    if request.method == "POST":
        form = GroupEditForm(request.POST, instance=group, use_required_attribute=False)

        if not form.errors:
            instance = form.save(commit=False)
            tags = request.POST.getlist("tags[]")

            if len(tags):
                if len(tags) > 5:
                    form.add_error(None, "Вы можете добавить не более 5 интересов.")
                else:
                    instance.tags.set(tags)
            else:
                form.add_error(None, "Добавьте хотя бы один интерес.")

            icon = request.FILES.get("icon")
            banner = request.FILES.get("banner")

            if icon:
                instance.icon = icon
            if banner:
                instance.banner = banner

            if not form.errors:
                instance.save()
                return redirect("group_detail", pk=pk)

        return render(
            request,
            "groups/edit_group.html",
            {
                "search_form": ProfileSearchForm(),
                "editable": form,
                "group": group,
                "tags": Interest.objects.all(),
            },
        )

    return render(
        request,
        "groups/edit_group.html",
        {
            "search_form": ProfileSearchForm(),
            "editable": GroupEditForm(use_required_attribute=False, instance=group),
            "group": group,
            "tags": Interest.objects.all(),
        },
    )


@login_required
def delete_group(request: HttpRequest, pk: int):
    group = Group.objects.get(pk=pk)

    if not group or request.user != group.created_by:
        return redirect("group_detail", pk=pk)

    if request.method == "POST":
        if request.POST.get("yes"):
            group.delete()
            request.user.profile.groups.remove(group)
            return redirect("my_groups")
        return redirect("group_detail", pk=pk)

    return render(
        request,
        "groups/delete_group.html",
        {
            "search_form": ProfileSearchForm(),
            "tags": Interest.objects.all(),
            "group": group,
        },
    )


@login_required
def join_group(request: HttpRequest, pk: int):
    group = get_object_or_404(Group, pk=pk)
    group.members.add(request.user)
    request.user.profile.groups.add(group)
    return redirect("group_detail", pk=pk)


@login_required
def leave_group(request: HttpRequest, pk: int):
    group = get_object_or_404(Group, pk=pk)
    group.members.remove(request.user)
    request.user.profile.groups.remove(group)
    return redirect("group_detail", pk=pk)

school21_case/templates/groups/create_group.html
{% extends "base.html" %}
{% load static %}
{% load add_class %}

{% block title %}Создание группы{% endblock %}
{% block description %}Создайте свою группу и пригласите в людей со схожими интересами{% endblock %}

{% block content %}

<div class="container">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title gradient-right">Создать группу</h4>
      </div>
      <div class="card-body">

        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card card-attention">
            <div class="card-header">
              <h4 class="card-title gradient-right">Баннер</h4>
            </div>
            <div class="card-body banner">
                <img class="img-fluid banner-img" src="{% static 'img/nobanner.png' %}" id="banner">
            </div>
            <input type="file" name="banner" accept="image/*" class="form-control" id="id_banner">
          </div>

          <div class="row">
            <div class="col-md-4">

              <div class="card card-attention">
                <div class="card-header">
                  <h4 class="card-title gradient-right">Аватар</h4>
                </div>
                <div class="card-body">
                  <div class="avatar-container">
                    <div class="avatar-img avatar avatar-xl">
                      <img src="{% static 'img/noicon.png' %}" class="rounded-circle img-fluid" id="icon">
                    </div>
                  </div>
                  <input type="file" name="icon" accept="image/*" class="form-control" id="id_icon">
                </div>
              </div>

            </div>

            <div class="col-md-8">

              <div class="card card-attention"> 
                <div class="card-header">
                  <h4 class="card-title gradient-right">Информация о группе</h4>
                </div>
                <div class="card-body">
                  {% for field in create_form %}
                  <div class="row-md-4 mb-3">
                    <div class="form-label gradient-right">{{ field.label_tag }}</div>
                    {{ field|add_class:"form-control edit-field" }}
                  </div>
                  {% endfor %}
                </div>
              </div>

              <div class="card card-attention"> 
                <div class="card-header">
                  <h4 class="card-title gradient-right">Интересы группы</h4>
                </div>
                <div class="card-body">
                  {% for tag in tags %}
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="{{ tag.id }}" id="id_{{ tag|lower }}" name="interests[]">
                    <label class="form-check-label gradient-right" for="id_{{ tag|lower }}">
                      {{ tag.name }}
                    </label>
                  </div>
                  {% endfor %}
                </div>
              </div>

            </div>

            {% if create_form.errors %}
              <div class="row">
                <div class="alert alert-danger">
                  {{ create_form.non_field_errors }}
                </div>
              </div>
            {% endif %}
            
            <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-primary">Создать</button>
            </div>

          </div>
        </form>
      </div>
    </div>
</div>

<script>
  document.getElementById('id_icon').addEventListener('change', function(event) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function(e) {
        const iconImg = document.getElementById('icon');
        iconImg.src = e.target.result;
      }
      reader.readAsDataURL(file);
    }
  });

  document.getElementById('id_banner').addEventListener('change', function(event) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function(e) {
        const bannerImg = document.getElementById('banner');
        bannerImg.src = e.target.result;
      }
      reader.readAsDataURL(file);
    }
  });
</script>
{% endblock %}

school21_case/templates/groups/delete_group.html
{% extends "base.html" %}
{% load static %}
{% load add_class %}

{% block title %}Удаление группы{% endblock %}
{% block description %}Подтвердите удаление группы{%endblock %}

{% block content %}

<div class="container">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Удаление группы</h4>
      </div>
      <div class="card-body">

      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card card-attention">
          <div class="card-header">
            <div class="d-flex justify-content-center">
              <h4 class="card-title text-info">Вы уверены, что хотите удалить группу <i class="card-title">{{ group.name }}</i> ?</h4>
            </div>
          </div>
          <div class="card-body">
            <div class="text-center">
              <div>
                <button type="submit" class="btn btn-primary text-danger mb-3" name="yes" value="yes">Да, удалите её</button>
              </div>
              <div>
                <button type="submit" class="btn btn-primary" name="no" value="no">Нет! Верните меня обратно!</button>
              </div>
            </div>
          </div>
        </div>
      </form>

      </div>
    </div>
</div>

{% endblock %}

school21_case/templates/groups/edit_group.html
{% extends "base.html" %}
{% load static %}
{% load add_class %}

{% block title %}Редактирование группы{% endblock %}
{% block description %}Редактирование группы {{ group.name }}{%endblock %}

{% block content %}

<div class="container">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Редактировать группу</h4>
      </div>
      <div class="card-body">

        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card card-attention">
            <div class="card-header">
              <h4 class="card-title">Баннер</h4>
            </div>
            <div class="card-body">
              <div class="banner">
                {% if group.banner %}
                  <img class="img-fluid banner-img" src="{{ group.banner.url }}" id="banner">
                {% else %}
                  <img class="img-fluid banner-img" src="{% static 'img/nobanner.png' %}" id="banner">
                {% endif %}
              </div>
            </div>
            <input type="file" name="banner" accept="image/*" class="form-control" id="id_banner">
          </div>

          <div class="row">
            <div class="col-md-4">

              <div class="card card-attention">
                <div class="card-header">
                  <h4 class="card-title">Аватар</h4>
                </div>
                <div class="card-body">
                  <div class="avatar-container">
                    <div class="avatar-img avatar avatar-xl">
                      {% if group.icon %}
                        <img src="{{ group.icon.url }}" class="rounded-circle img-fluid" id="icon">
                      {% else %}
                        <img src="{% static 'img/noicon.png' %}" class="rounded-circle img-fluid" id="icon">
                      {% endif %}
                    </div>
                  </div>
                  <input type="file" name="icon" accept="image/*" class="form-control" id="id_icon">
                </div>
              </div>

            </div>

            <div class="col-md-8">

              <div class="card card-attention"> 
                <div class="card-header">
                  <h4 class="card-title">Информация о группе</h4>
                </div>
                <div class="card-body">
                  {% for field in editable %}
                  <div class="row-md-4 mb-3">
                    <div class="form-label gradient-right">{{ field.label_tag }}</div>
                    {{ field|add_class:"form-control edit-field" }}
                  </div>
                  {% endfor %}
                </div>
              </div>

              <div class="card card-attention"> 
                <div class="card-header">
                  <h4 class="card-title">Интересы</h4>
                </div>
                <div class="card-body">
                  {% for tag in tags %}
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="{{ tag.id }}" id="id_{{ tag|lower }}" name="tags[]"
                    {% if tag in group.tags.all %}checked{% endif %}>
                    <label class="form-check-label gradient-right" for="id_{{ tag|lower }}">
                      {{ tag.name }}
                    </label>
                  </div>
                  {% endfor %}
                </div>
              </div>

            </div>

            {% if editable.errors %}
              <div class="row">
                <div class="alert alert-danger">
                  {% if editable.non_field_errors %}
                    {{ editable.non_field_errors }}
                  {% else %}
                    {{ editable.errors }}
                  {% endif %}
                </div>
              </div>
            {% endif %}
            
            <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Сохранить</button>
            </div>
          </div>
        </form>
        <a href="{% url 'group_detail' pk=group.pk %}">
          <button class="btn btn-primary">Назад</button>
        </a>
      </div>
    </div>
</div>

<script>
  document.getElementById('id_icon').addEventListener('change', function(event) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function(e) {
        const iconImg = document.getElementById('icon');
        iconImg.src = e.target.result;
      }
      reader.readAsDataURL(file);
    }
  });

  document.getElementById('id_banner').addEventListener('change', function(event) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function(e) {
        const bannerImg = document.getElementById('banner');
        bannerImg.src = e.target.result;
      }
      reader.readAsDataURL(file);
    }
  });
</script>
{% endblock %}

school21_case/templates/groups/find_groups.html
{% extends "base.html" %}
{% load static %}
{% load add_class %}

{% block title %}Поиск групп{% endblock %}
{% block description %}
{% if just_loaded %}
Найдите группу по названию или интересам
{% else %}
Результаты поиска
{% endif %}
Результаты поиска по запросу {{ search_query }}
{%endblock %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card card-round">
      <div class="card-header">
        <div class="card-head-row card-tools-still-right">
          <h4 class="card-title gradient-right"><i class="fas fa-search"></i> Поиск Групп</h4>
        </div>

        <div class="row mt-2">
          <form class="search-widget container-fluid" action="{% url 'find_groups' %}" method="POST">
              <div class="input-group rounded">
                <div class="input-group-append">
                  <button class="btn btn-primary btn-border dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Интересы
                  </button>
                  <div class="dropdown-menu">
                      {% for tag in tags %}
                      <div class="form-check">
                          <input class="form-check-input" type="checkbox" value="{{ tag.id }}" id="id_{{ tag|lower }}" name="interests[]"
                          {% if tag in group.tags.all %}checked{% endif %}>
                          <label class="form-check-label" for="id_{{ tag|lower }}">
                          {{ tag.name }}
                          </label>
                        </div>
                      {% endfor %}
                    </div>
                </div>
                  {% csrf_token %}
                  {% for field in find_group_form %}
                      {{ field|add_class:"form-control group-input" }}
                  {% endfor %}
                  <div class="input-group-append">
                      <button class="btn group-button" type="submit"><i class="fa fa-search"></i></button>
                  </div>
              </div>
          </form>
        </div>

        {% if not just_loaded %}
          {% if groups %}
          <p class="card-category"><i class="fas fa-search-plus"></i> Результаты поиска по запросу <i>{{ search_query }}</i></p>
          {% else %}
          <p class="card-category text-danger"><i class="fas fa-search-minus"></i> По вашему запросу <i>{{ search_query }}</i> ничего не найдено</p>
          {% endif %}
        {% endif %}

      </div>

      <div class="card-body">
        <div class="row">

          {% if groups and search_query %}
            {% for group in groups %}
            <div class="col-12 col-sm-6 col-lg-4">
              <div class="card card-attention">
                  <div class="card-body user-card">

                    <div class="avatar avatar-xxl">
                      {% if group.icon %}
                        <img class="avatar-xxl rounded-circle" src="{{ group.icon.url }}" alt="">
                      {% else %}
                        <img class="avatar-xxl rounded-circle" src="{% static 'img/noavatar.png' %}" alt="">
                      {% endif %}
                    </div>
                    <div class="user-info">
                      <a href="{% url 'group_detail' pk=group.pk %}"><span class="card-title">{{ group.name }}</span></a>
                      <span class="card-text" style="color: azure; font-size: 15px;">{{ group.description|truncatewords:20 }}</span>
                      <span class="card-category gradient-right" style="font-size: 17px;"><i class="fas fa-users"></i> {{ group.members.all|length }}</span>
                      <span class="card-text" style="color: azure; font-size: 15px;">{{ group.created_at }}</span>
                      <p class="card-category">{% for tag in group.tags.all %}#{{ tag }} {% endfor %}</p>
                    </div>

                  </div>

              </div>
            </div>
          {% endfor %}
          {% else %}
          <div class="text-center mb-3">
            <h4 class="card-title gradient-right"><i class="fas fa-user-astronaut"></i> Популярные Группы</h4>
          </div>
          {% for group in groups %}
            <div class="row-12 row-sm-6 row-lg-4">
              <div class="card card-attention">
                <div class="card-body user-card">

                  <div class="avatar avatar-xxl">
                    {% if group.icon %}
                      <img class="avatar-xxl rounded-circle" src="{{ group.icon.url }}" alt="">
                    {% else %}
                      <img class="avatar-xxl rounded-circle" src="{% static 'img/noavatar.png' %}" alt="">
                    {% endif %}
                  </div>
                  <div class="user-info">
                    <a href="{% url 'group_detail' pk=group.pk %}"><span class="card-title">{{ group.name }}</span></a>
                    <span class="card-text" style="color: azure; font-size: 15px;">{{ group.description|truncatewords:20 }}</span>
                    <span class="card-category gradient-right" style="font-size: 17px;"><i class="fas fa-users"></i> {{ group.members.all|length }}</span>
                    <span class="card-text" style="color: azure; font-size: 15px;">{{ group.created_at }}</span>
                    <p class="card-category">{% for tag in group.tags.all %}#{{ tag }} {% endfor %}</p>
                  </div>

                </div>

              </div>
            </div>
          {% endfor %}
          {% endif %}
      </div>
    </div>

  </div>
</div>

{% endblock %}

school21_case/templates/groups/group_members.html
{% extends "base.html" %}
{% load static %}

{% block title %}Участники группы {{ group.name }}{% endblock %}
{% block description %}{{ group.description|truncatewords:15 }}{%endblock %}

{% block content %}

<div class="container">
  <div class="card">
    <div class="card-header">
      <div class="card-head-row card-tools-still-right">
        <h4 class="card-title gradient-right"><i class="fas fa-users"></i> Участники группы</h4>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col">

          {% for member in members %}
            <div class="card card-attention">
              <div class="card-body user-card d-flex align-items-center">
                <div class="avatar avatar-xxl me-3">
                  {% if member.profile.avatar %}
                    <img class="avatar-xxl rounded-circle" src="{{ member.profile.avatar.url }}">
                  {% else %}
                    <img class="avatar-xxl rounded-circle" src="{% static 'img/noavatar.png' %}">
                  {% endif %}
                </div>
                <div class="user-info">
                  <a href="{% url 'profile_detail' pk=member.pk %}" class="text-decoration-none">
                    <span class="card-title">
                      {{ member.profile.nickname }}
                      {% if request.user == member %}
                        (Вы)
                      {% endif %}
                    </span>
                  </a>
                  <span class="card-text d-block" style="color: azure; font-size: 15px;">{{ member.profile.description|default:"Описание отстутствует"|truncatewords:15 }}</span>
                  <p class="card-category">{% for tag in member.profile.interests.all %}#{{ tag }} {% endfor %}</p>
                </div>
                <div class="col">
                  <p class="card-category"></p>
                </div>
              </div>
            </div>
          {% endfor %}

        </div>
      </div>

        <div class="row-md">
          {% if page_obj.has_next %}
          <div class="col">
            <div class="site-pagination p-3">
              {% if page_obj.has_previous %}
                {% if page_obj.previous_page_number > 1 %}
                <a href="?page=1">1</a>
                {% endif %}
                <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
              {% endif %}

              <span class="active">{{ page_obj.number }}</span>

              {% if page_obj.has_next %}
                  <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                  {% if page_obj.next_page_number < page_obj.paginator.num_pages %}
                      <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                  {% endif %}
              {% endif %}
            </div>
          </div>
          {% endif %}
          <div class="col">
            <div class="d-flex justify-content-center">
              <a href="{% url 'group_detail' pk=group_pk %}">
                <button class="btn btn-primary">Назад</button>
              </a>
            </div>
          </div>
        </div>

    </div>
  </div>
</div>

{% endblock %}

school21_case/templates/groups/my_groups.html
{% extends "base.html" %}
{% load static %}

{% block title %}Мои группы{% endblock %}
{% block description %}Группы в которых вы состоите{%endblock %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card card-round">
      <div class="card-header">
        <div class="card-head-row card-tools-still-right">
          <h4 class="card-title gradient-right"><i class="fas fa-users"></i> Мои Группы</h4>
        </div>
      </div>
      <div class="card-body">
        <div class="row">

        {% for group in groups %}
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="card card-attention">
              <div class="card-body user-card">

                <div class="avatar avatar-xxl">
                  {% if group.icon %}
                    <img class="avatar-xxl rounded-circle" src="{{ group.icon.url }}" alt="">
                  {% else %}
                    <img class="avatar-xxl rounded-circle" src="{% static 'img/noicon.png' %}" alt="">
                  {% endif %}
                </div>
                <div class="user-info">
                  <a href="{% url 'group_detail' pk=group.pk %}"><span class="card-title">
                  {% if group.created_by == user %}
                    <i class="fas fa-chess-king"></i>
                  {% endif %}
                    {{ group.name }}</span>
                  </a>
                  <span class="card-text" style="color: azure; font-size: 15px;">{{ group.description|truncatewords:20 }}</span>
                  <span class="card-text" style="color: azure; font-size: 15px;">{{ group.created_at }}</span>
                  <p class="card-category">{% for tag in group.tags.all %}#{{ tag }} {% endfor %}</p>
                </div>

              </div>
          </div>
        </div>
        {% endfor %}
      </div>

      </div>
    </div>
  </div>
</div>

{% endblock %}